### ISSUE TITLE
We should be testing the real templates, not fake templates within tests. 

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/beetmoverscript#116]
https://github.com/mozilla-releng/beetmoverscript/blob/master/beetmoverscript/test/fake_config.json#L16 should be pointing at real templates to have a minimum coverage there as well.

**Comment by MihaiTabara** [comment]
We're tracking this work in 1462393. Once we have templates in-tree, I'm hoping for tests there as well.

**Comment by MihaiTabara** [comment]
This will probably be retired once we have declarative artifacts. With the manifest in-tree we'll be able to implement testing there.

**Comment by lundjordan** [comment]
> This will probably be retired once we have declarative artifacts. With the manifest in-tree we'll be able to implement testing there.

@MihaiTabara - does this issue still apply given declarative artifacts?

**Comment by MihaiTabara** [comment]
We'll add tests in-tree at some point to check the routes. We can safely close this. Thanks for uncovering this.
