### ISSUE TITLE
Staging beetmover should generate balrog URLs that point at the staging bucket.

### ISSUE THREAD

**Issue by tomprince** [mozilla-releng/beetmoverscript#121]
Specifically, https://github.com/mozilla-releng/beetmoverscript/blob/7ac5f1143af2ad61c0e68b2c273b65a96591c6be/beetmoverscript/script.py#L371 should be updated to make `archive.mozilla.org` conditional on the bucket being used.

**Comment by MihaiTabara** [comment]
This got solved along the way with one of @tomprince's patches.
