### ISSUE TITLE
support chunkify behaviors for various types of tasks

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/beetmoverscript#177]
In a bunch of tasks in the release automation it'd make a lot of sense if we had support for chunks. Once we have declarative artifacts and maven within the new beetmoverscript, I think it'd be neat to support this as well rather than always needing to add countless beetmover jobs into the graph.

**Comment by lundjordan** [comment]
@MihaiTabara  - is this something we should track and prioritize in q2 as a post-declarative artifact project?

**Comment by MihaiTabara** [comment]
Hm, we already do some chunking in beetmover for langpacks. We could indeed expand the behavior. On the other hand the payload tasks would grow significantly if we did that. Not sure how to assess that workload.

At the very least, this is worth investigating and drawing some conclusion, before any work is being done.

**Comment by MihaiTabara** [comment]
Tracking it here - https://trello.com/c/nBA3vz9d/76-support-chunkify-behaviors-in-beetmover-jobs

**Comment by MihaiTabara** [comment]
I think this issue has outlived its purpose. Closing it, will resurface if we need it.
