### ISSUE TITLE
Update requests to 2.20.0

### ISSUE THREAD

**Issue by nthomas-mozilla** [mozilla-releng/beetmoverscript#192]
Github pointed out there's a security alert in requests 2.19.1 and lower - [more details](https://github.com/mozilla-releng/beetmoverscript/network/alert/requirements-prod.txt/requests/open).

**Comment by MihaiTabara** [comment]
Thanks for filing this. I'll prep a fix in the upcoming days!

**Comment by MihaiTabara** [comment]
Fixed by https://github.com/mozilla-releng/beetmoverscript/pull/193
