### ISSUE TITLE
buildhub.json's download.url is 404

### ISSUE THREAD

**Issue by rail** [mozilla-releng/beetmoverscript#195]
Looking at this [buildhub.json](https://download.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.buildhub.json) I see:

```json
"download": {
        "date": "2018-12-10T11:46:18.893852+00:00",
        "mimetype": "application/octet-stream",
        "size": 69585249,
        "url": "https://archive.mozilla.org/https%3A/archive.mozilla.org/2018/12/2018-12-10-09-55-04-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2"
    },
```

Looks like something went wrong with mangling the URL.

**Comment by MihaiTabara** [comment]
Oups, thanks for raising this. Might be a fallout from declarative artifacts PR. I'll have a look.

**Comment by rail** [comment]
I can review the fix ;)

**Comment by rail** [comment]
it's also interesting that it misses `pub/firefox/nightly` in the path.

**Comment by rail** [comment]
Something tells me that we should revert just one line [here](https://github.com/mozilla-releng/beetmoverscript/pull/185/files#diff-21f3f939e3375901322bd3639f4394bcR206). We definitely need the `s3_bucket_path` piece and shouldn't add `url_prefix` twice.

Maybe @srfraser has better context here.

**Comment by srfraser** [comment]
We need `s3_bucket_path` if we're not using the artifact map, but we don't need it if we're not. Maybe it's a case of moving line 204 above line 198, and having `url = urllib.parse.quote(urllib.parse.urljoin(manifest["s3_bucket_path"], dest[0]))` in the `else` block

**Comment by rail** [comment]
Something like [this](https://gist.github.com/adca82e19dab4dae0cc1245b36acba78)? Sorry, blindly trying to guess. :)

**Comment by srfraser** [comment]
Yes, that should be fine.
