### ISSUE TITLE
separate creds for release+nightly

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/beetmoverscript#28]
To improve security, ideally we'd have 3 sets of creds for firefox beetmover:

* dep (can push to staging / test area only)
* nightly (can push to nightly bucket only)
* release (can push to release bucket only)

and we'd choose which set of creds to use based on scopes.  `project:releng:beetmover:nightly` and `project:releng:beetmover:release` would be required to use either the nightly or release creds.

This would help us make sure we don't write to the wrong bucket from a low-security tree.

**Comment by MihaiTabara** [comment]
Solved via https://github.com/mozilla-releng/beetmoverscript/pull/51
