### ISSUE TITLE
update schema

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/beetmoverscript#97]
We are adding a lot of things in `task.payload` that don't seem to be covered by the schema... let's add them, even if they're optional.

**Comment by lundjordan** [comment]
@escapewindow - is this largely about taking anything in [taskgraph beetmover based templates](https://dxr.mozilla.org/mozilla-central/source/taskcluster/taskgraph/transforms/beetmover.py#299-319) and updating [beetmoverscript *schemas](https://github.com/mozilla-releng/beetmoverscript/tree/master/beetmoverscript/data)?

**Comment by escapewindow** [comment]
@lundjordan I think the former link should be https://dxr.mozilla.org/mozilla-central/source/taskcluster/taskgraph/transforms/task.py#973-1010 since that's the final piece that changes the task payload. Otherwise, yes.

**Comment by MihaiTabara** [comment]
Done via https://github.com/mozilla-releng/beetmoverscript/pull/137
